---
- name: Test Webhook Connection from ServiceNow
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Storage HealthCheck
      condition: event.payload.incident_details.short_description is search("RHEL-NodeFilesystemAlmostOutOfSpace")
      action:
        run_workflow_template:
          organization: "Default"
          name: "Disk-Health-Check"
          job_args:
            extra_vars:
              incident: "{{ event.payload.incident_details }}"
              hostname: "{{ event.payload.incident_details.cmdb_ci | lower }}"

    - name: Catch-all rule to print the webhook payload
      # This condition ensures the rule fires for ANY payload received
      condition: event.payload is defined
      action:
        debug:
          msg: "SUCCESS! Received a payload: {{ event.payload }}"
