---
- name: Launch the patching workflow
  hosts: localhost

  tasks:
    - name: Show me all the things
      ansible.builtin.debug:
        var: ansible_facts
    - name: set my fact
      ansible.builtin.set_fact:
        footy: "Go Blues"
    - name: preview fact
      ansible.builtin.debug:
        var: footy
      
